version: "3.8"

services:
  gpt4all_api:
    image: gpt4all_api
    container_name: gpt4all_api
    restart: always #restart on error (usually code compilation from save during bad state)
    ports:
      - "4891:4891"
    environment:
      - APP_ENVIRONMENT=dev
      - WEB_CONCURRENCY=4
      - LOGLEVEL=debug
      - PORT=4891
        # - model=ggml-mpt-7b-chat.bin (WORKS)
      - model=llama-2-7b-chat.ggmlv3.q4_0.bin
        # - model=llama-2-7b-chat.ggmlv3.q8_0.bin
      - inference_mode=cpu
      - n_threads=8
    volumes:
      - './gpt4all_api/app:/app'
      - '/home/ubuntu/models:/models'
    command: ["/start-reload.sh"]
